# -*- coding: utf-8 -*-
"""phi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MiDc0-trTRwxYiKcYMFSzar5QA0cLdIL
"""

import sympy as sp

# Define symbolic variable t
t = sp.symbols('t')

# System parameter values
M1 = 700  # kg
M2 = 90   # kg
k1 = 62000  # N/m
k2 = 570000  # N/m
b1 = 500    # N.s/m
b2 = 22500  # N.s/m

# System matrix A
A = sp.Matrix([[0, 1, 0, 0],
               [0, 0, -88.6, -0.7],
               [0, 0, 0, 1],
               [6333.3, 250, -7110.8, -256.3]])

# Calculate the state transition matrix Φ(t) = exp(A*t)
Phi_t = sp.exp(A * t)

print("State transition matrix Φ(t):")
sp.pprint(Phi_t)